export const brands = [

  { id: 2, name: "Bionatural", folder: "Bionatural", logo: "/Produtos/Marca/Bionatural.png" },
  { id: 1, name: "Fórmula Natural", folder: "Fórmula Natural", logo: "/Produtos/Marca/formlanatural.png" },
  { id: 7, name: "N&D", folder: "N&D", logo: "/Produtos/Marca/n&d.png" },
  { id: 9, name: "PremieR", folder: "PremieR", logo: "/Produtos/Marca/Premier.png" },
  { id: 10, name: "PremieR_Nattu", folder: "PremieR_Nattu", logo: "/Produtos/Marca/PremieR_Nattu.png" },
  { id: 14, name: "Marca", folder: "Marca", logo: "/Produtos/Marca/hills.avif" },
  { id: 3, name: "Finotrato", folder: "Finotrato", logo: "/Produtos/Marca/Finotrato.png" },
  { id: 11, name: "special Cat", folder: "special Cat", logo: "/Produtos/Marca/SpecialCat.png" },
  { id: 12, name: "Special dog", folder: "Special dog", logo: "/Produtos/Marca/SpecialDog.png" },
  { id: 13, name: "VittA_Natural", folder: "VittA_Natural", logo: "/Produtos/Marca/VittA_Natural.png" },
  { id: 8, name: "Origens", folder: "Origens", logo: "/Produtos/Marca/ORIGENS.png" },
  { id: 5, name: "GoldeN", folder: "GoldeN", logo: "/Produtos/Marca/golden.png" },
  { id: 6, name: "Magnus", folder: "Magnus", logo: "/Produtos/Marca/MAGNUS.png" },
  { id: 4, name: "Besser", folder: "Besser", logo: "/Produtos/Marca/Besser.png" }
];

export const produtosMock = [
  // Besser
  { id: 1, nome: "Besser Natural Cães Adultos", marca: "Besser", marcaPasta: "Besser", imagem: "/Produtos/Besser/Besser_Natural_Cães_Adultos.png", prioridade: 5 },
  { id: 2, nome: "Besser Natural Cães Adultos de Raças Pequenas e Médias", marca: "Besser", marcaPasta: "Besser", imagem: "/Produtos/Besser/Besser_Natural_Cães_Adultos_de_Raças_Pequenas_e_Médias.png", prioridade: 10 },
  { id: 3, nome: "Besser Natural Cães Filhotes", marca: "Besser", marcaPasta: "Besser", imagem: "/Produtos/Besser/Besser_Natural_Cães_Filhotes.png", prioridade: 15 },
  { id: 4, nome: "Besser Natural Gatos Filhotes", marca: "Besser", marcaPasta: "Besser", imagem: "/Produtos/Besser/Besser_Natural_Gatos_Filhotes.png", prioridade: 20 },
  // Bionatural
  { id: 5, nome: "Bionatural Adultos RAÇAS MÉDIAS E GRANDES Frango", marca: "Bionatural", marcaPasta: "Bionatural", imagem: "/Produtos/Bionatural/Bionatural_Adultos_RAÇAS MÉDIAS E GRANDES_Frango.png", prioridade: 8 },
  { id: 6, nome: "Bionatural Adultos RAÇAS PEQUENAS Cordeiro", marca: "Bionatural", marcaPasta: "Bionatural", imagem: "/Produtos/Bionatural/Bionatural_Adultos_RAÇAS PEQUENAS_Cordeiro.png", prioridade: 12 },
  { id: 7, nome: "Bionatural Adultos RAÇAS PEQUENAS Frango", marca: "Bionatural", marcaPasta: "Bionatural", imagem: "/Produtos/Bionatural/Bionatural_Adultos_RAÇAS PEQUENAS_Frango.png", prioridade: 18 },
  { id: 8, nome: "Bionatural Adultos salmao", marca: "Bionatural", marcaPasta: "Bionatural", imagem: "/Produtos/Bionatural/Bionatural_Adultos_salmao.png", prioridade: 25 },
  { id: 9, nome: "Bionatural Castrados Frango", marca: "Bionatural", marcaPasta: "Bionatural", imagem: "/Produtos/Bionatural/Bionatural_Castrados_Frango.png", prioridade: 30 },
  { id: 10, nome: "Bionatural Castrados Salmao", marca: "Bionatural", marcaPasta: "Bionatural", imagem: "/Produtos/Bionatural/Bionatural_Castrados_Salmao.png", prioridade: 35 },
  { id: 11, nome: "Bionatural Junior RAÇAS PEQUENAS Frango", marca: "Bionatural", marcaPasta: "Bionatural", imagem: "/Produtos/Bionatural/Bionatural_Junior_RAÇAS PEQUENAS_Frango.png", prioridade: 40 },
  { id: 12, nome: "Bionatural RAÇAS MÉDIAS E GRANDES Cordeiro", marca: "Bionatural", marcaPasta: "Bionatural", imagem: "/Produtos/Bionatural/Bionatural_RAÇAS MÉDIAS E GRANDES_Cordeiro.png", prioridade: 45 },
  { id: 13, nome: "Bionatural Senior RAÇAS PEQUENAS Frango", marca: "Bionatural", marcaPasta: "Bionatural", imagem: "/Produtos/Bionatural/Bionatural_Senior_RAÇAS PEQUENAS_Frango.png", prioridade: 50 },
  // Finotrato (36 produtos)
  { id: 14, nome: "Finotrato Bifinho Carne - Cães", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Bifinho_Carne_-_Cães.png" },
  { id: 15, nome: "Finotrato Bifinho Frango - Cães", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Bifinho_Frango_-_Cães.png" },
  { id: 16, nome: "Finotrato Bio-Litter", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Bio-Litter.png" },
  { id: 17, nome: "Finotrato Cat Nuggets Sabor Carne - Gatos Adultos", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Cat_Nuggets_Sabor_Carne_-_Gatos_Adultos.png" },
  { id: 18, nome: "Finotrato Cat Stix Atum", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Cat_Stix_Atum.png" },
  { id: 19, nome: "Finotrato Cat Stix Carne", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Cat_Stix_Carne.png" },
  { id: 20, nome: "Finotrato Cat Stix Frango", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Cat_Stix_Frango.png" },
  { id: 21, nome: "Finotrato Cat Stix Salmão", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Cat_Stix_Salmão.png" },
  { id: 22, nome: "Finotrato Dog Stix Carne", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Dog_Stix_Carne.png" },
  { id: 23, nome: "Finotrato Dog Stix Frango", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Dog_Stix_Frango.png" },
  { id: 24, nome: "Finotrato Gold Cães Adultos de Raças Mini e Pequenas", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Gold_Cães_Adultos_de_Raças_Mini_e_Pequenas.png" },
  { id: 25, nome: "Finotrato Gold Cães Adultos de Raças Médias e Grandes", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Gold_Cães_Adultos_de_Raças_Médias_e_Grandes.png" },
  { id: 26, nome: "Finotrato Gold Cães Filhotes de Raças Mini e Pequenas", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Gold_Cães_Filhotes_de_Raças_Mini_e_Pequenas.png" },
  { id: 27, nome: "Finotrato Gold Cães Filhotes de Raças Médias e Grandes", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Gold_Cães_Filhotes_de_Raças_Médias_e_Grandes.png" },
  { id: 28, nome: "Finotrato Gold Salmão e Frango Gatos Adultos", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Gold_Salmão_e_Frango_Gatos_Adultos.png" },
  { id: 29, nome: "Finotrato Gold Salmão e Frango Gatos Castrados", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Gold_Salmão_e_Frango_Gatos_Castrados.png" },
  { id: 30, nome: "Finotrato Gold Salmão e Frango Gatos Filhotes", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Gold_Salmão_e_Frango_Gatos_Filhotes.png" },
  { id: 31, nome: "Finotrato Life Active Frango e Arroz Cães Adultos", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Life_Active_Frango_e_Arroz_Cães_Adultos.png" },
  { id: 32, nome: "Finotrato Life Active Frango e Arroz Cães Filhotes", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Life_Active_Frango_e_Arroz_Cães_Filhotes.png" },
  { id: 33, nome: "Finotrato Life Light Frango e Arroz Cães Adultos de Raças Grandes", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Life_Light_Frango_e_Arroz_Cães_Adultos_de_Raças_Grandes.png" },
  { id: 34, nome: "Finotrato Life Light Frango e Arroz Cães Adultos de Raças Pequenas e Médias", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Life_Light_Frango_e_Arroz_Cães_Adultos_de_Raças_Pequenas_e_Médias.png" },
  { id: 35, nome: "Finotrato Life Sensitive Cordeiro e Arroz Cães Adultos de Raças Pequenas e Médias", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Life_Sensitive_Cordeiro_e_Arroz_Cães_Adultos_de_Raças_Pequenas_e_Médias.png" },
  { id: 36, nome: "Finotrato Life Sênior Frango e Arroz Cães Senis de Raças Grandes", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Life_Sênior_Frango_e_Arroz_Cães_Senis_de_Raças_Grandes.png" },
  { id: 37, nome: "Finotrato Life Sênior Frango e Arroz Cães Senis de Raças Pequenas e Médias", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Life_Sênior_Frango_e_Arroz_Cães_Senis_de_Raças_Pequenas_e_Médias.png" },
  { id: 38, nome: "Finotrato Nature Cães Adultos de Raças Grandes", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Nature_Cães_Adultos_de_Raças_Grandes.png" },
  { id: 39, nome: "Finotrato Nature Cães Adultos de Raças Pequenas e Médias", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Nature_Cães_Adultos_de_Raças_Pequenas_e_Médias.png" },
  { id: 40, nome: "Finotrato Nature Cães Filhotes de Raças Pequenas e Médias", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Nature_Cães_Filhotes_de_Raças_Pequenas_e_Médias.png" },
  { id: 41, nome: "Finotrato Patê Carne - Cães Adultos", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Patê_Carne_-_Cães_Adultos.png" },
  { id: 42, nome: "Finotrato Patê Carne - Cães Filhotes", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Patê_Carne_-_Cães_Filhotes.png" },
  { id: 43, nome: "Finotrato Prime Carne e Arroz Cães Adultos de Raças Grandes", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Prime_Carne_e_Arroz_Cães_Adultos_de_Raças_Grandes.png" },
  { id: 44, nome: "Finotrato Prime Carne e Arroz Cães Adultos de Raças Pequenas e Médias", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Prime_Carne_e_Arroz_Cães_Adultos_de_Raças_Pequenas_e_Médias.png" },
  { id: 45, nome: "Finotrato Prime Frango e Arroz Cães Adultos de Raças Grandes", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Prime_Frango_e_Arroz_Cães_Adultos_de_Raças_Grandes.png" },
  { id: 46, nome: "Finotrato Prime Frango e Arroz Cães Adultos de Raças Pequenas e Médias", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Prime_Frango_e_Arroz_Cães_Adultos_de_Raças_Pequenas_e_Médias.png" },
  { id: 47, nome: "Finotrato Prime Frango e Arroz Cães Filhotes de Raças Pequenas e Médias", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Prime_Frango_e_Arroz_Cães_Filhotes_de_Raças_Pequenas_e_Médias.png" },
  { id: 48, nome: "Finotrato Select Cães Adultos", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Select_Cães_Adultos.png" },
  { id: 49, nome: "Finotrato Select Cães Adultos Raças Pequenas e Médias", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Select_Cães_Adultos_Raças_Pequenas_e_Médias.png" },
  { id: 50, nome: "Finotrato Select Gatos Adultos", marca: "Finotrato", marcaPasta: "Finotrato", imagem: "/Produtos/Finotrato/Finotrato_Select_Gatos_Adultos.png" },
  // Fórmula Natural (30 produtos)
  { id: 51, nome: "Fórmula Natural Dog Biscuits Batata Doce, Banana e Linhaça Pequeno Porte", marca: "Fórmula Natural", marcaPasta: "Fórmula Natural", imagem: "/Produtos/Fórmula Natural/Fórmula Natural Dog Biscuits Batata Doce, Banana e Linhaça Pequeno Porte.png" },
  { id: 52, nome: "Fórmula Natural Life Cães Adultos Portes Médio e Grande", marca: "Fórmula Natural", marcaPasta: "Fórmula Natural", imagem: "/Produtos/Fórmula Natural/Fórmula Natural Life Cães Adultos Portes Médio e Grande.png" },
  { id: 53, nome: "Fórmula Natural Life Cães Filhotes Portes Mini e Pequeno", marca: "Fórmula Natural", marcaPasta: "Fórmula Natural", imagem: "/Produtos/Fórmula Natural/Fórmula Natural Life Cães Filhotes Portes Mini e Pequeno.png" },
  { id: 54, nome: "Fórmula Natural Life Cão Sênior Portes Mini e Pequeno", marca: "Fórmula Natural", marcaPasta: "Fórmula Natural", imagem: "/Produtos/Fórmula Natural/Fórmula Natural Life Cão Sênior Portes Mini e Pequeno.png" },
  { id: 55, nome: "Fórmula Natural Life Cão Sênior Portes Médio e Grande", marca: "Fórmula Natural", marcaPasta: "Fórmula Natural", imagem: "/Produtos/Fórmula Natural/Fórmula Natural Life Cão Sênior Portes Médio e Grande.png" },
  { id: 56, nome: "Fórmula Natural Pro Cães Adultos Portes Mini e Pequeno", marca: "Fórmula Natural", marcaPasta: "Fórmula Natural", imagem: "/Produtos/Fórmula Natural/Fórmula Natural Pro Cães Adultos Portes Mini e Pequeno.png" },
  { id: 57, nome: "Fórmula Natural Pro Cães Adultos Portes Médio e Grande", marca: "Fórmula Natural", marcaPasta: "Fórmula Natural", imagem: "/Produtos/Fórmula Natural/Fórmula Natural Pro Cães Adultos Portes Médio e Grande.png" },
  { id: 58, nome: "Fórmula Natural Pro Cães Filhotes Portes Médio e Grande", marca: "Fórmula Natural", marcaPasta: "Fórmula Natural", imagem: "/Produtos/Fórmula Natural/Fórmula Natural Pro Cães Filhotes Portes Médio e Grande.png" },
  { id: 59, nome: "Fórmula Natural Receitas Caseiras Cães Adultos Cordeiro com Batata e Hortelã", marca: "Fórmula Natural", marcaPasta: "Fórmula Natural", imagem: "/Produtos/Fórmula Natural/Fórmula Natural Receitas Caseiras Cães Adultos Cordeiro com Batata e Hortelã.png" },
  { id: 60, nome: "Fórmula Natural Receitas Caseiras Cães Adultos Picadinho de Carne com Abóbora e Mandioquinha", marca: "Fórmula Natural", marcaPasta: "Fórmula Natural", imagem: "/Produtos/Fórmula Natural/Fórmula Natural Receitas Caseiras Cães Adultos Picadinho de Carne com Abóbora e Mandioquinha.png" },
  { id: 61, nome: "Fórmula Natural Receitas Caseiras Gatos Adultos Carne", marca: "Fórmula Natural", marcaPasta: "Fórmula Natural", imagem: "/Produtos/Fórmula Natural/Fórmula Natural Receitas Caseiras Gatos Adultos Carne.png" },
  { id: 62, nome: "Fórmula Natural Receitas Caseiras Gatos Adultos Salmão com Maracujá ao Molho", marca: "Fórmula Natural", marcaPasta: "Fórmula Natural", imagem: "/Produtos/Fórmula Natural/Fórmula Natural Receitas Caseiras Gatos Adultos Salmão com Maracujá ao Molho.png" },
  { id: 63, nome: "Fórmula Natural Snacks Antiestresse Cães Adultos Portes Mini e Pequeno", marca: "Fórmula Natural", marcaPasta: "Fórmula Natural", imagem: "/Produtos/Fórmula Natural/Fórmula Natural Snacks Antiestresse Cães Adultos Portes Mini e Pequeno.png" },
  { id: 64, nome: "Fórmula Natural Snacks Antiestresse Cães Adultos Portes Médio e Grande", marca: "Fórmula Natural", marcaPasta: "Fórmula Natural", imagem: "/Produtos/Fórmula Natural/Fórmula Natural Snacks Antiestresse Cães Adultos Portes Médio e Grande.png" },
  { id: 65, nome: "Fórmula Natural Snacks Vitalidade Cães Adultos Portes Mini e Pequeno", marca: "Fórmula Natural", marcaPasta: "Fórmula Natural", imagem: "/Produtos/Fórmula Natural/Fórmula Natural Snacks Vitalidade Cães Adultos Portes Mini e Pequeno.png" },
  { id: 66, nome: "Fórmula Natural Vet Care Renal Gatos Úmido", marca: "Fórmula Natural", marcaPasta: "Fórmula Natural", imagem: "/Produtos/Fórmula Natural/Fórmula Natural Vet Care Renal Gatos Úmido.png" },
  { id: 67, nome: "Fórmula Natural-LIFE_ADULTOS_MINI-E-PEQUENO", marca: "Fórmula Natural", marcaPasta: "Fórmula Natural", imagem: "/Produtos/Fórmula Natural/Fórmula Natural-LIFE_ADULTOS_MINI-E-PEQUENO.png" },
  { id: 68, nome: "Fórmula Natural_LIFE_CAES_FILHOTES Portes Médio e Grande", marca: "Fórmula Natural", marcaPasta: "Fórmula Natural", imagem: "/Produtos/Fórmula Natural/Fórmula Natural_LIFE_CAES_FILHOTES Portes Médio e Grande.png" },
  { id: 69, nome: "Fórmula_Natural_Fresh_Meat_Controle_De_Peso_Cães_Adultos_Portes_Mini_e_Pequeno", marca: "Fórmula Natural", marcaPasta: "Fórmula Natural", imagem: "/Produtos/Fórmula Natural/Fórmula_Natural_Fresh_Meat_Controle_De_Peso_Cães_Adultos_Portes_Mini_e_Pequeno.png" },
  { id: 70, nome: "Fórmula_Natural_FRESH_MEAT_CUIDADO_ORAL_Portes_Mini_e_Pequeno", marca: "Fórmula Natural", marcaPasta: "Fórmula Natural", imagem: "/Produtos/Fórmula Natural/Fórmula_Natural_FRESH_MEAT_CUIDADO_ORAL_Portes_Mini_e_Pequeno.png" },
  { id: 71, nome: "Fórmula_Natural_Fresh_Meat_Cães_Adultos_Portes_Mini_e_Pequeno....", marca: "Fórmula Natural", marcaPasta: "Fórmula Natural", imagem: "/Produtos/Fórmula Natural/Fórmula_Natural_Fresh_Meat_Cães_Adultos_Portes_Mini_e_Pequeno....png" },
  { id: 72, nome: "Fórmula_Natural_Fresh_Meat_Cães_Adultos_Porte_Médio", marca: "Fórmula Natural", marcaPasta: "Fórmula Natural", imagem: "/Produtos/Fórmula Natural/Fórmula_Natural_Fresh_Meat_Cães_Adultos_Porte_Médio.png" },
  { id: 73, nome: "Fórmula_Natural_Fresh_Meat_Cães_Filhotes_Portes_Mini_e_Pequeno....", marca: "Fórmula Natural", marcaPasta: "Fórmula Natural", imagem: "/Produtos/Fórmula Natural/Fórmula_Natural_Fresh_Meat_Cães_Filhotes_Portes_Mini_e_Pequeno....png" },
  { id: 74, nome: "Fórmula_Natural_Fresh_Meat_Cão_Sênior_Portes_Mini_e_Pequeno", marca: "Fórmula Natural", marcaPasta: "Fórmula Natural", imagem: "/Produtos/Fórmula Natural/Fórmula_Natural_Fresh_Meat_Cão_Sênior_Portes_Mini_e_Pequeno.png" },
  { id: 75, nome: "Fórmula_Natural_Fresh_Meat_Cão_Sênior_Portes_Médio_e_Grande", marca: "Fórmula Natural", marcaPasta: "Fórmula Natural", imagem: "/Produtos/Fórmula Natural/Fórmula_Natural_Fresh_Meat_Cão_Sênior_Portes_Médio_e_Grande.png" },
  { id: 76, nome: "Fórmula_Natural_Fresh_Meat_Gatos_Adultos_Frango", marca: "Fórmula Natural", marcaPasta: "Fórmula Natural", imagem: "/Produtos/Fórmula Natural/Fórmula_Natural_Fresh_Meat_Gatos_Adultos_Frango.png" },
  { id: 77, nome: "Fórmula_Natural_Fresh_Meat_Gatos_Castrados_Carne", marca: "Fórmula Natural", marcaPasta: "Fórmula Natural", imagem: "/Produtos/Fórmula Natural/Fórmula_Natural_Fresh_Meat_Gatos_Castrados_Carne.png" },
  { id: 78, nome: "Fórmula_Natural_Fresh_Meat_Gatos_Castrados_Salmão", marca: "Fórmula Natural", marcaPasta: "Fórmula Natural", imagem: "/Produtos/Fórmula Natural/Fórmula_Natural_Fresh_Meat_Gatos_Castrados_Salmão.png" },
  { id: 79, nome: "Fórmula_Natural_Fresh_Meat_Gatos_Sênior", marca: "Fórmula Natural", marcaPasta: "Fórmula Natural", imagem: "/Produtos/Fórmula Natural/Fórmula_Natural_Fresh_Meat_Gatos_Sênior.png" },
  { id: 80, nome: "Fórmula_Natural_Fresh_Meat_Sensitive_Cães_Adultos_Portes_Mini_e_Pequeno", marca: "Fórmula Natural", marcaPasta: "Fórmula Natural", imagem: "/Produtos/Fórmula Natural/Fórmula_Natural_Fresh_Meat_Sensitive_Cães_Adultos_Portes_Mini_e_Pequeno.png" },
  { id: 81, nome: "Fórmula_Natural_Life_Gatos_Castrados_Sabor_Frango", marca: "Fórmula Natural", marcaPasta: "Fórmula Natural", imagem: "/Produtos/Fórmula Natural/Fórmula_Natural_Life_Gatos_Castrados_Sabor_Frango.png" },
  // GoldeN (17 produtos)
  { id: 82, nome: "GoldeN Formula Cães Adultos Porte Pequeno Carne e Arroz", marca: "GoldeN", marcaPasta: "GoldeN", imagem: "/Produtos/GoldeN/GoldeN_Formula_Cães_Adultos_Porte_Pequeno_Carne_e_Arroz.png" },
  { id: 83, nome: "GoldeN Formula Cães Adultos Porte Pequeno Frango & Arroz", marca: "GoldeN", marcaPasta: "GoldeN", imagem: "/Produtos/GoldeN/GoldeN_Formula_Cães_Adultos_Porte_Pequeno_Frango_&_Arroz.png" },
  { id: 84, nome: "GoldeN Formula Cães Adultos Porte Pequeno Frango & Arroz Light", marca: "GoldeN", marcaPasta: "GoldeN", imagem: "/Produtos/GoldeN/GoldeN_Formula_Cães_Adultos_Porte_Pequeno_Frango_&_Arroz_Light.png" },
  { id: 85, nome: "GoldeN Formula Cães Adultos Porte Pequeno Peru & Arroz", marca: "GoldeN", marcaPasta: "GoldeN", imagem: "/Produtos/GoldeN/GoldeN_Formula_Cães_Adultos_Porte_Pequeno_Peru_&_Arroz.png" },
  { id: 86, nome: "GoldeN Formula Cães Filhotes Carne & Arroz", marca: "GoldeN", marcaPasta: "GoldeN", imagem: "/Produtos/GoldeN/GoldeN_Formula_Cães_Filhotes_Carne_&_Arroz.png" },
  { id: 87, nome: "GoldeN Formula Cães Filhotes Frango & Arroz", marca: "GoldeN", marcaPasta: "GoldeN", imagem: "/Produtos/GoldeN/GoldeN_Formula_Cães_Filhotes_Frango_&_Arroz.png" },
  { id: 88, nome: "GoldeN Formula Cães Filhotes Porte Pequeno Frango & Arroz", marca: "GoldeN", marcaPasta: "GoldeN", imagem: "/Produtos/GoldeN/GoldeN_Formula_Cães_Filhotes_Porte_Pequeno_Frango_&_Arroz.png" },
  { id: 89, nome: "GoldeN Formula Cães Seniores Porte Pequeno Frango e Arroz Mini Bits", marca: "GoldeN", marcaPasta: "GoldeN", imagem: "/Produtos/GoldeN/GoldeN_Formula_Cães_Seniores_Porte_Pequeno_Frango_e_Arroz_Mini_Bits.png" },
  { id: 90, nome: "GoldeN Gatos Adultos Carne", marca: "GoldeN", marcaPasta: "GoldeN", imagem: "/Produtos/GoldeN/GoldeN_Gatos_Adultos_Carne.png" },
  { id: 91, nome: "GoldeN Gatos Adultos Frango", marca: "GoldeN", marcaPasta: "GoldeN", imagem: "/Produtos/GoldeN/GoldeN_Gatos_Adultos_Frango.png" },
  { id: 92, nome: "GoldeN Gatos Adultos Salmão", marca: "GoldeN", marcaPasta: "GoldeN", imagem: "/Produtos/GoldeN/GoldeN_Gatos_Adultos_Salmão.png" },
  { id: 93, nome: "GoldeN Gatos Castrados Carne", marca: "GoldeN", marcaPasta: "GoldeN", imagem: "/Produtos/GoldeN/GoldeN_Gatos_Castrados_Carne.png" },
  { id: 94, nome: "GoldeN Gatos Castrados Frango", marca: "GoldeN", marcaPasta: "GoldeN", imagem: "/Produtos/GoldeN/GoldeN_Gatos_Castrados_Frango.png" },
  { id: 95, nome: "GoldeN Gatos Castrados Salmão", marca: "GoldeN", marcaPasta: "GoldeN", imagem: "/Produtos/GoldeN/GoldeN_Gatos_Castrados_Salmão.png" },
  { id: 96, nome: "GoldeN Gatos Filhotes Frango", marca: "GoldeN", marcaPasta: "GoldeN", imagem: "/Produtos/GoldeN/GoldeN_Gatos_Filhotes_Frango.png" },
  { id: 97, nome: "GoldeN Special Cães Adultos Porte Pequeno Frango e Carne", marca: "GoldeN", marcaPasta: "GoldeN", imagem: "/Produtos/GoldeN/GoldeN_Special_Cães_Adultos_Porte_Pequeno_Frango_e_Carne.png" },
  { id: 98, nome: "GoldeN Special Cães Filhotes Porte Pequeno Frango e Carne", marca: "GoldeN", marcaPasta: "GoldeN", imagem: "/Produtos/GoldeN/GoldeN_Special_Cães_Filhotes_Porte_Pequeno_Frango_e_Carne.png" },
  // Magnus (7 produtos)
  { id: 99, nome: "Magnus Bifinhos Cães Sabor Carne", marca: "Magnus", marcaPasta: "Magnus", imagem: "/Produtos/Magnus/Magnus_Bifinhos_Cães_Sabor_Carne.png" },
  { id: 100, nome: "Magnus Bifinhos Cães Sabor Frango", marca: "Magnus", marcaPasta: "Magnus", imagem: "/Produtos/Magnus/Magnus_Bifinhos_Cães_Sabor_Frango.png" },
  { id: 101, nome: "Magnus Biscoito Cães Adultos Pequeno Porte", marca: "Magnus", marcaPasta: "Magnus", imagem: "/Produtos/Magnus/Magnus_Biscoito_Cães_Adultos_Pequeno_Porte.png" },
  { id: 102, nome: "Magnus Biscoito Mix Cães Adultos", marca: "Magnus", marcaPasta: "Magnus", imagem: "/Produtos/Magnus/Magnus_Biscoito_Mix_Cães_Adultos.png" },
  { id: 103, nome: "Magnus Todo Dia Cães Adultos Pequeno Porte Sabor Carne e Frango", marca: "Magnus", marcaPasta: "Magnus", imagem: "/Produtos/Magnus/Magnus_Todo_Dia_Cães_Adultos_Pequeno_Porte_Sabor_Carne_e_Frango.png" },
  { id: 104, nome: "Magnus Todo Dia Cães Adultos Sabor Carne", marca: "Magnus", marcaPasta: "Magnus", imagem: "/Produtos/Magnus/Magnus_Todo_Dia_Cães_Adultos_Sabor_Carne.png" },
  { id: 105, nome: "Magnus Todo Dia Cães Filhotes Sabor Carne", marca: "Magnus", marcaPasta: "Magnus", imagem: "/Produtos/Magnus/Magnus_Todo_Dia_Cães_Filhotes_Sabor_Carne.png" },
  // N&D (12 produtos)
  { id: 106, nome: "N&D TROPICAL SELECTION CANINE CORDEIRO ADULT MINI", marca: "N&D", marcaPasta: "N&D", imagem: "/Produtos/N&D/N&D TROPICAL SELECTION CANINE CORDEIRO ADULT MINI.png", prioridade: 76 },
  { id: 107, nome: "N&D TROPICAL SELECTION CANINE CORDEIRO PUPPY MINI", marca: "N&D", marcaPasta: "N&D", imagem: "/Produtos/N&D/N&D TROPICAL SELECTION CANINE CORDEIRO PUPPY MINI.png", prioridade: 77 },
  { id: 108, nome: "N&D TROPICAL SELECTION CANINE FRANGO ADULT MINI", marca: "N&D", marcaPasta: "N&D", imagem: "/Produtos/N&D/N&D TROPICAL SELECTION CANINE FRANGO ADULT MINI.png", prioridade: 78 },
  { id: 109, nome: "N&D TROPICAL SELECTION CANINE SALMÃO ADULT MINI", marca: "N&D", marcaPasta: "N&D", imagem: "/Produtos/N&D/N&D TROPICAL SELECTION CANINE SALMÃO ADULT MINI.png", prioridade: 79 },
  { id: 110, nome: "N&D TROPICAL SELECTION CANINE SUÍNO ADULT MINI", marca: "N&D", marcaPasta: "N&D", imagem: "/Produtos/N&D/N&D TROPICAL SELECTION CANINE SUÍNO ADULT MINI.png", prioridade: 80 },
  { id: 111, nome: "N&D TROPICAL SELECTION CANINE SUÍNO PUPPY MINI", marca: "N&D", marcaPasta: "N&D", imagem: "/Produtos/N&D/N&D TROPICAL SELECTION CANINE SUÍNO PUPPY MINI.png", prioridade: 81 },
  { id: 112, nome: "n&d Ancestral Canine Cordeiro Adulto Mini", marca: "N&D", marcaPasta: "N&D", imagem: "/Produtos/N&D/n&d_Ancestral_Canine_Cordeiro_Adulto_Mini.png", prioridade: 82 },
  { id: 113, nome: "n&d cao-white-puppy-mini", marca: "N&D", marcaPasta: "N&D", imagem: "/Produtos/N&D/n&d_cao-white-puppy-mini.png", prioridade: 83 },
  { id: 114, nome: "n&d cao ANCESTRAL ADULT MEDIUM", marca: "N&D", marcaPasta: "N&D", imagem: "/Produtos/N&D/n&d_cao_ANCESTRAL_ADULT_MEDIUM.png", prioridade: 84 },
  { id: 115, nome: "N&D cao White Adult Mini - Merluza, Spirulina e Erva Doce", marca: "N&D", marcaPasta: "N&D", imagem: "/Produtos/N&D/N&D_cao_White Adult Mini - Merluza, Spirulina e Erva Doce.png", prioridade: 85 },
  { id: 116, nome: "n&d gatos Frango Adult Castrados", marca: "N&D", marcaPasta: "N&D", imagem: "/Produtos/N&D/n&d_gatos_Frango Adult Castrados.png", prioridade: 86 },
  { id: 117, nome: "n&d Gatos Tilápia, Spirulina e Goji Berry Adult", marca: "N&D", marcaPasta: "N&D", imagem: "/Produtos/N&D/n&d_Gatos_Tilápia, Spirulina e Goji Berry Adult.png", prioridade: 87 },
  // Origens (16 produtos)
  { id: 118, nome: "Origens Class Cães Adultos Portes Mini e Pequeno", marca: "Origens", marcaPasta: "Origens", imagem: "/Produtos/Origens/Origens Class Cães Adultos Portes Mini e Pequeno.png", prioridade: 88 },
  { id: 119, nome: "Origens Dental Cães", marca: "Origens", marcaPasta: "Origens", imagem: "/Produtos/Origens/Origens Dental Cães.png", prioridade: 89 },
  { id: 120, nome: "Origens Energy Cães Adultos Sabor Frango e Cereais", marca: "Origens", marcaPasta: "Origens", imagem: "/Produtos/Origens/Origens Energy Cães Adultos Sabor Frango e Cereais.png", prioridade: 90 },
  { id: 121, nome: "Origens Petiscos Naturais Traqueia Bovina", marca: "Origens", marcaPasta: "Origens", imagem: "/Produtos/Origens/Origens Petiscos Naturais Traqueia Bovina.png", prioridade: 91 },
  { id: 122, nome: "Origens Raças Específicas Cães Adultos Shih Tzu e Lhasa Apso", marca: "Origens", marcaPasta: "Origens", imagem: "/Produtos/Origens/Origens Raças Específicas Cães Adultos Shih Tzu e Lhasa Apso.png", prioridade: 92 },
  { id: 123, nome: "Origens Raças Específicas Cães Adultos Yorkshire, Maltês e Spitz", marca: "Origens", marcaPasta: "Origens", imagem: "/Produtos/Origens/Origens Raças Específicas Cães Adultos Yorkshire, Maltês e Spitz.png", prioridade: 93 },
  { id: 124, nome: "Origens Cães Adultos Portes Mini e Pequeno Sabor Carne", marca: "Origens", marcaPasta: "Origens", imagem: "/Produtos/Origens/Origens_Cães_Adultos_Portes_Mini_e_Pequeno_Sabor_Carne.png", prioridade: 94 },
  { id: 125, nome: "Origens Cães Adultos Portes Mini e Pequeno Sabor Frango", marca: "Origens", marcaPasta: "Origens", imagem: "/Produtos/Origens/Origens_Cães_Adultos_Portes_Mini_e_Pequeno_Sabor_Frango.png", prioridade: 95 },
  { id: 126, nome: "Origens Cães Adultos Sabor Carne e Cereais", marca: "Origens", marcaPasta: "Origens", imagem: "/Produtos/Origens/Origens_Cães_Adultos_Sabor_Carne_e_Cereais.png", prioridade: 96 },
  { id: 127, nome: "Origens Cães Sênior Portes Mini e Pequeno", marca: "Origens", marcaPasta: "Origens", imagem: "/Produtos/Origens/Origens_Cães_Sênior_Portes_Mini_e_Pequeno.png", prioridade: 97 },
  { id: 128, nome: "Origens Premium Especial Gatos Adultos Sabor Carne", marca: "Origens", marcaPasta: "Origens", imagem: "/Produtos/Origens/Origens_Premium_Especial_Gatos_Adultos_Sabor_Carne.png", prioridade: 98 },
  { id: 129, nome: "Origens Premium Especial Gatos Adultos Sabor Frango", marca: "Origens", marcaPasta: "Origens", imagem: "/Produtos/Origens/Origens_Premium_Especial_Gatos_Adultos_Sabor_Frango.png", prioridade: 99 },
  { id: 130, nome: "Origens Premium Especial Gatos Castrados Sabor Carne", marca: "Origens", marcaPasta: "Origens", imagem: "/Produtos/Origens/Origens_Premium_Especial_Gatos_Castrados_Sabor_Carne.png", prioridade: 100 },
  { id: 131, nome: "Origens Premium Especial Gatos Castrados Sabor Frango", marca: "Origens", marcaPasta: "Origens", imagem: "/Produtos/Origens/Origens_Premium_Especial_Gatos_Castrados_Sabor_Frango.png", prioridade: 101 },
  { id: 132, nome: "Origens Premium Especial Gatos Castrados Sabor Salmão", marca: "Origens", marcaPasta: "Origens", imagem: "/Produtos/Origens/Origens_Premium_Especial_Gatos_Castrados_Sabor_Salmão.png", prioridade: 102 },
  { id: 133, nome: "Origens Premium Especial Gatos Filhotes Sabor Frango e Cereais", marca: "Origens", marcaPasta: "Origens", imagem: "/Produtos/Origens/Origens_Premium_Especial_Gatos_Filhotes_Sabor_Frango_e_Cereais.png", prioridade: 103 },
  // PremieR (18 produtos)
  { id: 134, nome: "PremieR Ambientes Internos Cães Adultos Porte Pequeno Frango e Salmão", marca: "PremieR", marcaPasta: "PremieR", imagem: "/Produtos/PremieR/PremieR_Ambientes_Internos_Cães_Adultos_Porte_Pequeno_Frango_e_Salmão.png", prioridade: 104 },
  { id: 135, nome: "PremieR Ambientes Internos Cães Adultos Porte Pequeno Frango e Salmão Castrados", marca: "PremieR", marcaPasta: "PremieR", imagem: "/Produtos/PremieR/PremieR_Ambientes_Internos_Cães_Adultos_Porte_Pequeno_Frango_e_Salmão_Castrados.png", prioridade: 105 },
  { id: 136, nome: "PremieR Ambientes Internos Cães Adultos Porte Pequeno Frango e Salmão Light", marca: "PremieR", marcaPasta: "PremieR", imagem: "/Produtos/PremieR/PremieR_Ambientes_Internos_Cães_Adultos_Porte_Pequeno_Frango_e_Salmão_Light.png", prioridade: 106 },
  { id: 137, nome: "PremieR Ambientes Internos Cães Adultos Porte Pequeno Frango e Salmão Senior", marca: "PremieR", marcaPasta: "PremieR", imagem: "/Produtos/PremieR/PremieR_Ambientes_Internos_Cães_Adultos_Porte_Pequeno_Frango_e_Salmão_Senior.png", prioridade: 107 },
  { id: 138, nome: "PremieR Ambientes Internos Cães Adultos Porte Pequeno Salmão Dermacare", marca: "PremieR", marcaPasta: "PremieR", imagem: "/Produtos/PremieR/PremieR_Ambientes_Internos_Cães_Adultos_Porte_Pequeno_Salmão_Dermacare.png", prioridade: 108 },
  { id: 139, nome: "PremieR Ambientes Internos Cães Filhotes Porte Pequeno Frango e Salmão", marca: "PremieR", marcaPasta: "PremieR", imagem: "/Produtos/PremieR/PremieR_Ambientes_Internos_Cães_Filhotes_Porte_Pequeno_Frango_e_Salmão.png", prioridade: 109 },
  { id: 140, nome: "PremieR Formula Cães Adultos Porte Médio Frango", marca: "PremieR", marcaPasta: "PremieR", imagem: "/Produtos/PremieR/PremieR_Formula_Cães_Adultos_Porte_Médio_Frango.png", prioridade: 110 },
  { id: 141, nome: "PremieR Formula Cães Adultos Porte Pequeno Frango", marca: "PremieR", marcaPasta: "PremieR", imagem: "/Produtos/PremieR/PremieR_Formula_Cães_Adultos_Porte_Pequeno_Frango.png", prioridade: 111 },
  { id: 142, nome: "PremieR Formula Cães Filhotes Porte Pequeno Frango", marca: "PremieR", marcaPasta: "PremieR", imagem: "/Produtos/PremieR/PremieR_Formula_Cães_Filhotes_Porte_Pequeno_Frango.png", prioridade: 112 },
  { id: 143, nome: "PremieR Raças Específicas Bulldog Francês Adultos Porte Pequeno Frango", marca: "PremieR", marcaPasta: "PremieR", imagem: "/Produtos/PremieR/PremieR_Raças_Específicas_Bulldog_Francês_Adultos_Porte_Pequeno_Frango.png", prioridade: 113 },
  { id: 144, nome: "PremieR Raças Específicas Bulldog Inglês Adultos Porte Médio Frango", marca: "PremieR", marcaPasta: "PremieR", imagem: "/Produtos/PremieR/PremieR_Raças_Específicas_Bulldog_Inglês_Adultos_Porte_Médio_Frango.png", prioridade: 114 },
  { id: 145, nome: "PremieR Raças Específicas Filhotes Frango Bulldog Francês", marca: "PremieR", marcaPasta: "PremieR", imagem: "/Produtos/PremieR/PremieR_Raças_Específicas_Filhotes_Frango_Bulldog_Francês.png", prioridade: 115 },
  { id: 146, nome: "PremieR Raças Específicas Shih Tzu Adultos Porte Pequeno Frango", marca: "PremieR", marcaPasta: "PremieR", imagem: "/Produtos/PremieR/PremieR_Raças_Específicas_Shih_Tzu_Adultos_Porte_Pequeno_Frango.png", prioridade: 116 },
  { id: 147, nome: "PremieR Raças Específicas Shih Tzu Filhotes Porte Pequeno Frango", marca: "PremieR", marcaPasta: "PremieR", imagem: "/Produtos/PremieR/PremieR_Raças_Específicas_Shih_Tzu_Filhotes_Porte_Pequeno_Frango.png", prioridade: 117 },
  { id: 148, nome: "PremieR Raças Específicas Spitz Alemão Adulto Porte Pequeno Frango", marca: "PremieR", marcaPasta: "PremieR", imagem: "/Produtos/PremieR/PremieR_Raças_Específicas_Spitz_Alemão_Adulto_Porte_Pequeno_Frango.png", prioridade: 118 },
  { id: 149, nome: "PremieR Raças Específicas Spitz Alemão Filhotes Porte Pequeno Frango", marca: "PremieR", marcaPasta: "PremieR", imagem: "/Produtos/PremieR/PremieR_Raças_Específicas_Spitz_Alemão_Filhotes_Porte_Pequeno_Frango.png", prioridade: 119 },
  { id: 150, nome: "PremieR Raças Específicas Yorkshire Adultos Porte Pequeno Frango", marca: "PremieR", marcaPasta: "PremieR", imagem: "/Produtos/PremieR/PremieR_Raças_Específicas_Yorkshire_Adultos_Porte_Pequeno_Frango.png", prioridade: 120 },
  { id: 151, nome: "PremieR Raças Específicas Yorkshire Filhotes Porte Pequeno Frango", marca: "PremieR", marcaPasta: "PremieR", imagem: "/Produtos/PremieR/PremieR_Raças_Específicas_Yorkshire_Filhotes_Porte_Pequeno_Frango.png", prioridade: 121 },
  // PremieR_Nattu (5 produtos)
  { id: 152, nome: "PremieR Nattu Cães Adultos Porte Pequeno Frango, Abóbora, Brócolis, Quinoa & Blueberry", marca: "PremieR_Nattu", marcaPasta: "PremieR_Nattu", imagem: "/Produtos/PremieR_Nattu/PremieR_Nattu_Cães_Adultos_Porte_Pequeno_Frango,_Abóbora,_Brócolis,_Quinoa_&_Blueberry.png", prioridade: 122 },
  { id: 153, nome: "PremieR Nattu Cães Adultos Porte Pequeno Frango, Mandioca, Beterraba, Linhaça & Cranberry", marca: "PremieR_Nattu", marcaPasta: "PremieR_Nattu", imagem: "/Produtos/PremieR_Nattu/PremieR_Nattu_Cães_Adultos_Porte_Pequeno_Frango,_Mandioca,_Beterraba,_Linhaça_&_Cranberry.png", prioridade: 123 },
  { id: 154, nome: "PremieR Nattu Cães Adultos Porte Pequeno Frango Mandioquinha, Espinafre, Cúrcuma & Blackberry", marca: "PremieR_Nattu", marcaPasta: "PremieR_Nattu", imagem: "/Produtos/PremieR_Nattu/PremieR_Nattu_Cães_Adultos_Porte_Pequeno_Frango_Mandioquinha,_Espinafre,_Cúrcuma_&_Blackberry.png", prioridade: 124 },
  { id: 155, nome: "PremieR Nattu Cães Filhotes Porte Pequeno Frango, Mandioca, Beterraba, Linhaça e Cranberry", marca: "PremieR_Nattu", marcaPasta: "PremieR_Nattu", imagem: "/Produtos/PremieR_Nattu/PremieR_Nattu_Cães_Filhotes_Porte_Pequeno_Frango,_Mandioca,_Beterraba,_Linhaça_e_Cranberry.png", prioridade: 125 },
  { id: 156, nome: "PremieR Nattu Cães Sênior Porte Pequeno Frango, Mandioca, Beterraba, Linhaça & Cranberry", marca: "PremieR_Nattu", marcaPasta: "PremieR_Nattu", imagem: "/Produtos/PremieR_Nattu/PremieR_Nattu_Cães_Sênior_Porte_Pequeno_Frango,_Mandioca,_Beterraba,_Linhaça_&_Cranberry.png", prioridade: 126 },
  // special Cat (7 produtos)
  { id: 157, nome: "Special Cat Adultos Mix", marca: "special Cat", marcaPasta: "special Cat", imagem: "/Produtos/special Cat/Special Cat_Adultos_Mix.png", prioridade: 127 },
  { id: 158, nome: "Special Cat Castrados Mix", marca: "special Cat", marcaPasta: "special Cat", imagem: "/Produtos/special Cat/Special Cat_Castrados_Mix.png", prioridade: 128 },
  { id: 159, nome: "Special Cat Ultralife Adultos Frango", marca: "special Cat", marcaPasta: "special Cat", imagem: "/Produtos/special Cat/Special Cat_Ultralife_Adultos Frango.png", prioridade: 129 },
  { id: 160, nome: "Special Cat Ultralife Adultos Salmão", marca: "special Cat", marcaPasta: "special Cat", imagem: "/Produtos/special Cat/Special Cat_Ultralife_Adultos Salmão.png", prioridade: 130 },
  { id: 161, nome: "Special Cat Ultralife Castrados Frango", marca: "special Cat", marcaPasta: "special Cat", imagem: "/Produtos/special Cat/Special Cat_Ultralife_Castrados Frango.png", prioridade: 131 },
  { id: 162, nome: "Special Cat Ultralife Castrados10+ Salmão", marca: "special Cat", marcaPasta: "special Cat", imagem: "/Produtos/special Cat/Special Cat_Ultralife_Castrados10+Salmão.png", prioridade: 132 },
  { id: 163, nome: "Special Cat Ultralife Filhotes Salmão", marca: "special Cat", marcaPasta: "special Cat", imagem: "/Produtos/special Cat/Special Cat_Ultralife_Filhotes Salmão.png", prioridade: 133 },
  // Special dog (13 produtos)
  { id: 164, nome: "Special Dog-Sacaria-Performance-Junior-", marca: "Special dog", marcaPasta: "Special dog", imagem: "/Produtos/Special dog/Special Dog-Sacaria-Performance-Junior-.png", prioridade: 134 },
  { id: 165, nome: "SPECIAL DOG Adultos Carne", marca: "Special dog", marcaPasta: "Special dog", imagem: "/Produtos/Special dog/SPECIAL DOG_Adultos_Carne.png", prioridade: 135 },
  { id: 166, nome: "SPECIAL DOG Adultos Pequeno Porte Carne", marca: "Special dog", marcaPasta: "Special dog", imagem: "/Produtos/Special dog/SPECIAL DOG_Adultos_Pequeno Porte_Carne.png", prioridade: 136 },
  { id: 167, nome: "Special Dog Ultralife Adultos RAÇAS MÉDIAS E GRANDES", marca: "Special dog", marcaPasta: "Special dog", imagem: "/Produtos/Special dog/Special Dog_Ultralife_Adultos RAÇAS MÉDIAS E GRANDES.png", prioridade: 137 },
  { id: 168, nome: "Special Dog Ultralife Adultos RAÇAS PEQUENAS", marca: "Special dog", marcaPasta: "Special dog", imagem: "/Produtos/Special dog/Special Dog_Ultralife_Adultos RAÇAS PEQUENAS.png", prioridade: 138 },
  { id: 169, nome: "Special Dog Ultralife Adultos RAÇAS PEQUENAS Cordeiro", marca: "Special dog", marcaPasta: "Special dog", imagem: "/Produtos/Special dog/Special Dog_Ultralife_Adultos RAÇAS PEQUENAS_Cordeiro.png", prioridade: 139 },
  { id: 170, nome: "Special Dog Ultralife Junior RAÇAS MÉDIAS E GRANDES", marca: "Special dog", marcaPasta: "Special dog", imagem: "/Produtos/Special dog/Special Dog_Ultralife_Junior RAÇAS MÉDIAS E GRANDES.png", prioridade: 140 },
  { id: 171, nome: "Special Dog Ultralife Junior RAÇAS PEQUENAS", marca: "Special dog", marcaPasta: "Special dog", imagem: "/Produtos/Special dog/Special Dog_Ultralife_Junior RAÇAS PEQUENAS.png", prioridade: 141 },
  { id: 172, nome: "Special Dog Ultralife Light RAÇAS MÉDIAS E GRANDES", marca: "Special dog", marcaPasta: "Special dog", imagem: "/Produtos/Special dog/Special Dog_Ultralife_Light RAÇAS MÉDIAS E GRANDES.png", prioridade: 142 },
  { id: 173, nome: "Special Dog Ultralife Light RAÇAS PEQUENAS", marca: "Special dog", marcaPasta: "Special dog", imagem: "/Produtos/Special dog/Special Dog_Ultralife_Light RAÇAS PEQUENAS.png", prioridade: 143 },
  { id: 174, nome: "Special Dog Ultralife Performance", marca: "Special dog", marcaPasta: "Special dog", imagem: "/Produtos/Special dog/Special Dog_Ultralife_Performance_.png", prioridade: 144 },
  { id: 175, nome: "Special Dog Ultralife Senior RAÇAS MÉDIAS E GRANDES", marca: "Special dog", marcaPasta: "Special dog", imagem: "/Produtos/Special dog/Special Dog_Ultralife_Senior RAÇAS MÉDIAS E GRANDES.png", prioridade: 145 },
  { id: 176, nome: "Special Dog Ultralife Senior RAÇAS PEQUENAS", marca: "Special dog", marcaPasta: "Special dog", imagem: "/Produtos/Special dog/Special Dog_Ultralife_Senior RAÇAS PEQUENAS.png", prioridade: 146 },
  // VittA_Natural (7 produtos)
  { id: 177, nome: "VittA Natural Cães Adultos Carne e Arroz", marca: "VittA_Natural", marcaPasta: "VittA_Natural", imagem: "/Produtos/VittA_Natural/VittA_Natural_Cães_Adultos_Carne_e_Arroz.png", prioridade: 147 },
  { id: 178, nome: "VittA Natural Cães Adultos Frango e Arroz", marca: "VittA_Natural", marcaPasta: "VittA_Natural", imagem: "/Produtos/VittA_Natural/VittA_Natural_Cães_Adultos_Frango_e_Arroz.png", prioridade: 148 },
  { id: 179, nome: "VittA Natural Cães Adultos Porte Pequeno Carne e Arroz", marca: "VittA_Natural", marcaPasta: "VittA_Natural", imagem: "/Produtos/VittA_Natural/VittA_Natural_Cães_Adultos_Porte_Pequeno_Carne_e_Arroz.png", prioridade: 149 },
  { id: 180, nome: "VittA Natural Cães Adultos Porte Pequeno Frango e Arroz", marca: "VittA_Natural", marcaPasta: "VittA_Natural", imagem: "/Produtos/VittA_Natural/VittA_Natural_Cães_Adultos_Porte_Pequeno_Frango_e_Arroz.png", prioridade: 150 },
  { id: 181, nome: "VittA Natural Cães Filhotes Carne e Arroz", marca: "VittA_Natural", marcaPasta: "VittA_Natural", imagem: "/Produtos/VittA_Natural/VittA_Natural_Cães_Filhotes_Carne_e_Arroz.png", prioridade: 151 },
  { id: 182, nome: "Vitta Natural Cães Filhotes Frango e Arroz", marca: "VittA_Natural", marcaPasta: "VittA_Natural", imagem: "/Produtos/VittA_Natural/Vitta_Natural_Cães_Filhotes_Frango_e_Arroz.png", prioridade: 152 },
  { id: 183, nome: "VittA Natural Cães Filhotes Porte Pequeno Frango e Arroz", marca: "VittA_Natural", marcaPasta: "VittA_Natural", imagem: "/Produtos/VittA_Natural/VittA_Natural_Cães_Filhotes_Porte_Pequeno_Frango_e_Arroz.png", prioridade: 153 }
];